config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'words#index'
  resources :words
  resources :games, only: %i[new create show]
  resources :answers, only: %i[create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :user

  def correctness
    return '-' if total_answers_count.zero?

    value = (good_answers_count.to_f / bad_answers_count) * 100
    value.round(2)
    value.to_s + '%'
  end

  private

  def total_answers_count
    good_answers_count + bad_answers_count
  end
end

app/models/language.rb
# frozen_string_literal: true

class Language < ApplicationRecord
  has_many :words, dependent: :destroy
  validates :name, presence: true
  validates :name, inclusion: { in: LanguageList::COMMON_LANGUAGES.map(&:name) }
end

app/models/translation.rb
# frozen_string_literal: true

class Translation < ApplicationRecord
  belongs_to :word
  belongs_to :translated_word, class_name: 'Word'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :words, dependent: :destroy
  has_many :games, dependent: :destroy

  def secret_email
    email.gsub(/.{0,4}@/, '####@')
  end
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  belongs_to :language
  belongs_to :user

  has_many :translations_association, class_name: 'Translation'
  has_many :translations, through: :translations_association, source: :translated_word, dependent: :destroy
  has_many :inverse_translations_association, class_name: 'Translation', foreign_key: 'translated_word_id'
  has_many :inverse_translations, through: :inverse_translations_association, source: :word

  validates :content, :language, presence: true
  validate :translations_cannot_be_in_the_same_language_as_word

  accepts_nested_attributes_for :translations, allow_destroy: true

  paginates_per 10

  private

  def translations_cannot_be_in_the_same_language_as_word
    return if translations.none? { |translation| translation.language == language }

    errors.add(:language, 'must be different than language of translations.')
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[create]

  def create
    authorize(game, :access?)
    checker = Words::CheckAnswer.new(word, game, answer)
    @checker = checker.call
    respond_to do |format|
      format.js
    end
  end

  private

  def word
    Word.find(params[:answer][:word_id])
  end

  def answer
    params[:answer][:content]
  end

  def game
    Game.find(params[:answer][:game_id])
  end


end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :authenticate_user!, only: %i[create show]

  def create
    game = current_user.games.create
    redirect_to(game)
  end

  def show
    @game = Game.find(params[:id])
    authorize @game
    @word = Words::RandomWord.new.call
  end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update edit destroy]
  before_action :set_word, only: %i[show edit update destroy]

  def index
    @words = Word.includes(:user, :language, :translations).page(params[:page])
  end

  def new
    @word = current_user.words.new
    @word.translations.new
  end

  def create
    @word = Word.new(word_params)
    @word.user = current_user
    set_user_for_translations(@word)
    if @word.save
      redirect_to(words_path)
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize @word
  end

  def update
    authorize @word
    @word.assign_attributes(word_params)
    set_user_for_translations(@word)

    if @word.save
      redirect_to(word_path(@word))
    else
      render :edit
    end
  end

  def destroy
    authorize @word
    @word.destroy
    redirect_to(words_path)
  end

  private

  def word_params
    params.require(:word).permit(:content, :language_id,
                                 translations_attributes: %i[id content language_id _destroy])
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def set_user_for_translations(word)
    word.translations.each do |translation|
      translation.user = current_user
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}",
                                        role: 'alert') do
               concat(content_tag(:button, '×', class: 'close', data: { dismiss: 'alert' }))
               concat(message)
             end)
    end
    nil
  end
end

app/views/answers/create.js.erb
<%	if @checker == true  %>
  $('#answer_content').addClass('bg-success');
<% else %>
  $('#answer_content').addClass('bg-danger');
<%	end %>

location.reload();

setTimeout(function () {
    location.reload();
}, 2000)

app/views/games/show.html.haml
.jumbotron.text-center
  %h1.display-4= @word.content
  = simple_form_for :answer, url: answers_path, method: :post, remote: true do |f|
    = f.input :content, label: false, as: :string, input_html: { autocomplete: 'off', autofocus: true }
    = f.input :word_id, as: :hidden, input_html: { value: @word.id }
    = f.input :game_id, as: :hidden, input_html: { value: @game.id }
    = f.submit 'Check answer', as: :stirng, class: 'btn btn-primary btn-lg'
  %p
    %table.table
      %thead
        %tr
          %th.table-success Good Answers
          %th.table-danger Bad Answers
          %th.table-warning Correctness
      %tbody
        %tr
          %td.table-success= @game.good_answers_count
          %td.table-danger= @game.bad_answers_count
          %td.table-warning= @game.correctness

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dictionary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.mt-2
      = render 'shard/navbar'
      = render 'shard/messages'
      .container-fluid
        .row
          .col-md-12.mt-3
            = yield

app/views/shard/_messages.html.haml
.container-fluid.mt-4
  .row
    .col-md-12
      = flash_messages

app/views/shard/_navbar.html.haml
.container-fluid
  .row
    .col-md-12
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %a.navbar-brand{href: root_path} EnglPl
        %ul.navbar-nav
          - if user_signed_in?
            %li.nav-item
              = link_to('Create New Word', new_word_path, class: 'nav-link')
            - if current_user.games.present?
              %li.nav-item
              = link_to('Continue game', game_path(current_user.games.last), class: 'nav-link')
            - else
              %li.nav-item
                = link_to('Start new game', games_path, method: :post, class: 'nav-link')
          - if user_signed_in?
            %li.nav-item
              = link_to('Edit regestration', edit_user_registration_path, class: 'nav-link')
          - else
            %li.nav-item
              = link_to('Register', new_user_registration_path, class: 'nav-link')
          - if user_signed_in?
            %li.nav-item
              = link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link')
          - else
            %li.nav-item
              = link_to('Login', new_user_session_path, class: 'nav-link')

app/views/shard/_navs.html.haml
.container-fluid
  .row
    .col-md-12
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %a.navbar-brand{href: root_path} EnglPl
        %ul.navbar-nav
          - if user_signed_in?
            %li.nav-item
              = link_to('Create New Word', new_word_path, class: 'nav-link')
          - if user_signed_in?
            %li.nav-item
              = link_to('Edit regestration', edit_user_registration_path, class: 'nav-link')
          - else
            %li.nav-item
              = link_to('Register', new_user_registration_path, class: 'nav-link')
          - if user_signed_in?
            %li.nav-item
              = link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link')
          - else
            %li.nav-item
              = link_to('Login', new_user_session_path, class: 'nav-link')

app/views/words/_form.html.haml
= simple_nested_form_for @word do |f|
  = f.input :content
  = f.association :language
  %h3 Translations
  = f.fields_for :translations do |t|
    = t.input :content
    = t.association :language
    = t.link_to_remove('Remove this translation')
  %p= f.link_to_add('Add a new translation', :translations)
  = f.button :submit, class: 'btn btn-primary'

app/views/words/edit.html.haml
%h1 Edit Words

= render 'form'

app/views/words/index.html.haml
%h1 All words

%table.table
  %thead
    %tr
      %th
        \#
      %th
        Value
      %th
        Language
      %th
        User
      %th
        Translations Count
      %th
        Actions
  %tbody
    - @words.each do |word|
      %tr
        %td
          = word.id
        %td
          = word.content
        %td
          = word.language.name
        %td
          = word.user&.secret_email
        %td
          = word.translations.size
        %td
          = link_to('Show', word_path(word), class: 'btn btn-primary')
          - if user_signed_in? && policy(word).edit? && policy(word).destroy?
            = link_to('Edit', edit_word_path(word), class: 'btn btn-warning')
            = link_to('Delete', word_path(word), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure you want to delete this post'},)
= paginate @words

app/views/words/new.html.haml
%h1 New words

= render 'form'

app/views/words/show.html.haml
%h1= @word.content

%p
  Language:
  = @word.language&.name
%p
  %h3 User:
  = @word.user&.email

- if @word.translations.any?
  %h3 Translations:
  %p
    = @word.translations.pluck(:content).join(', ')